project_includes = ["helion", "examples"]
python_version = "3.10"

permissive-ignores = true

search-path = ["triton/python", "../pytorch", "../pytorch-hg", "../pytorch-nightly"]

untyped-def-behavior = "check-and-infer-return-any"

[errors]
implicitly-defined-attribute = false