project_includes = ["helion", "examples"]
project_excludes = ["venv", "triton"]
python_version = "3.10"
search_path = ["triton/python", "triton/third_party", "../pytorch", "../pytorch-hg", "../pytorch-nightly"] #, "typings"]
replace_imports_with_any = [
    # "torch.*"
]

site_package_path = [
  "venv/lib/python3.12/site-packages/",

]

# untyped-def-behavior = "check-and-infer-return-any"
# # [errors]
# # bad-override = false
# # bad-assignment = false
# # missing-attribute = false
# # read-only = false