project_includes = ["helion", "examples"]
python_version = "3.10"

permissive-ignores = true

search-path = ["triton/python", "../pytorch", "../pytorch-hg", "../pytorch-nightly"]
infer-with-first-use = false
errors.missing-attribute = false
